### ISSUE TITLE
STAR memory issue

### ISSUE THREAD

**Issue by kmkocot** [sagnikbanerjee15/Finder#12]
Hello! I'm very excited about this new tool but running into an issue early on in the pipeline. The file star_index_without_transcriptome.error is reporting this:

`EXITING because of FATAL PARAMETER ERROR: limitGenomeGenerateRAM=31000000000is too small for your genome
SOLUTION: please specify --limitGenomeGenerateRAM not less than 43903877386 and make that much RAM available 

Apr 22 14:59:38 ...... FATAL ERROR, exiting`

I have enough RAM but don't know how to indicate that to STAR.

Thanks!
Kevin

**Comment by sagnikbanerjee15** [comment]
Hello @kmkocot,

Thank you so much for checking out `finder`. The reason why you are getting that error is due to the size of the genome. The default RAM size is too small for your genome size. I have modified the code. You should be able to run it now. Please let me know if you run into any errors.

Thank you.

**Comment by kmkocot** [comment]
Thanks so much!
