### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dabitz** [sagnikbanerjee15/Finder#16]
Hi,

Thanks for the nice tool. I am trying to run finder on my own plant genome, but I am getting this error

EXITING: Did not find the genome in memory, did not remove any genomes from shared memory

May 25 22:17:31 ...... FATAL ERROR, exiting

It must be something simple, but I think I am missing something here...

Best,
André

**Comment by sagnikbanerjee15** [comment]
Hi @dabitz,

Thank you so much for trying out `finder`. For aligning short reads to the reference genome, `finder` uses `STAR`. Sometimes, if a run fails and `finder` is relaunched again, then `STAR` may not remove the program from the memory that it loaded in the previous run. Hence, at the beginning `finder` removes any memory footprint of previous iterations of `STAR`. This command means that `STAR` has exited but not `finder`. Let me know how the execution proceeds and feel free to report any issues you may encounter.

Thank you.

**Comment by dabitz** [comment]
Thanks, but it seems finder also exits after this error.. see the complete log error attached
[FINDER_test_RBREVI.error.txt](https://github.com/sagnikbanerjee15/Finder/files/6544715/FINDER_test_RBREVI.error.txt)

**Comment by sagnikbanerjee15** [comment]
Hello @dabitz,

That's not supposed to happen! Could you please share your metadata file and also the compressed output folder? I need to see each error file. 

Thank you.

**Comment by dabitz** [comment]
[Rhynchospora_breviuscula_metadata.csv](https://github.com/sagnikbanerjee15/Finder/files/6546565/Rhynchospora_breviuscula_metadata.csv)

[FINDER_test_RBREVI.output.txt](https://github.com/sagnikbanerjee15/Finder/files/6546568/FINDER_test_RBREVI.output.txt)
[FINDER_test_RBREVI.tar.gz](https://github.com/sagnikbanerjee15/Finder/files/6546577/FINDER_test_RBREVI.tar.gz)


here are the files

**Comment by sagnikbanerjee15** [comment]
Hello @dabitz,

Thank you for sending the data. I checked the metadata file and I am not sure the location is specified correctly. It's best to mention a full path on the location. For example, if the location of an RNA-Seq sample is `/work/LAS/fredrick-lab/abel/reads/x234.fastq` then you need to put `/work/LAS/fredrick-lab/abel/reads` in the location column of the metadata and `x234` in the SRA Accession column. For paired-ended reads, you do not need to explicitly mention both files. `finder` will construct the location from the information provided in the metadata. Since the location of the input RNA-Seq files were not correct, `STAR` was unable to find them. I checked one of `STAR's` output and indeed it failed since it was unable to locate the fastq files.

```
EXITING because of fatal input ERROR: could not open readFilesIn=reads/9_Rb6_1.fastq

May 26 09:16:51 ...... FATAL ERROR, exiting
```

Some users have expressed concerns about the metadata format. We are working to figure out a way to address the issue and make it easier for users.

Please let me know if you run into any other issues.

Thank you.

**Comment by dabitz** [comment]
It still not working, but I think the problem is that finder is looking for a .fastq file but my files are .fq.gz

**Comment by sagnikbanerjee15** [comment]
Oh, I see. Give me some time I will update the code to accept .fq.gz files too.

Thanks.

**Comment by sagnikbanerjee15** [comment]
Hi @dabitz,

I have updated the code. It should work on .fq.gz files too. Please note that the fix I made is rather fast and will get the work done for now. I will optimize the fix in a few days. Please let me know if you run into any issues.

Thank you.
