### ISSUE TITLE
Braker2 and new release

### ISSUE THREAD

**Issue by biouserPD** [sagnikbanerjee15/Finder#27]
Hi,
I would like to use finder to annotate a genome but I read in a previous post that a new version should come out without braker2, which can cause several problems. Do you think it's better to wait for the new release or use this one?
Thanks

**Comment by sagnikbanerjee15** [comment]
Hello @biouserPD,

Thank you so much for your interest in `finder`. We are currently working to accelerate the release of the new version but I can't be certain of the time when it will be released. Please go ahead and use the current version and let me know if you encounter any issues. `finder` will work as is but we noticed some issues with `braker` which is why we decided to eliminate it from our pipeline. I will let you know when the new version is available.

Thanks.
