### ISSUE TITLE
Help check legit of Finder for report in University

### ISSUE THREAD

**Issue by trungnl08** [sagnikbanerjee15/Finder#49]
Hi. I have a report about gene prediction tool for bioinformatics in university.And, i want to write a report about your tool but when search google, i only can find 1 artical : [https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04120-9](url) but not enought legit for it. I'm seeing your project still develop. Can you give me more link artical or something about your tool for me, thanks! 
btw, i will call all of my friends give heart for your github 💯

**Comment by sagnikbanerjee15** [comment]
Hello @trungnl08,

Thank you for your interest in `finder`. It is great that you wish to write a report on it. I will be more than happy to help you with any questions that you may have. Since this is not a software issue, we can move the discussion elsewhere. Please email me at sagnikbanerjee15@gmail.com.

Also, loads of thanks for spreading the word. It really helps!!

Thank you.
