### ISSUE TITLE
Question about final gtf files

### ISSUE THREAD

**Issue by josruirod** [sagnikbanerjee15/Finder#8]
Hi, so I've sucessfully completed few finder runs and I'm currently assessing the results. I'm finding it difficult to decide which one of all the provided would the more "final". For example, I'm getting less than 500 exons in the braker_utr.gtf, while in the "combined_with_CDS_BRAKER_appended_high_conf.gtf" (is this one repetitive with "combined_with_CDS_high_conf.gtf"?), which I understand couldbe the final one, I'm getting ~15000. So I'm a bit confused. Do you have any comment?

Thanks for the good support

**Comment by sagnikbanerjee15** [comment]
Hi @josruirod,

Thank you for your question. Yes, I agree it could get confusing with so many different options. I intentionally had `finder` generate several files so that the user gets to choose whatever file that best suits his/her purpose. Both braker.gtf and braker_utr.gtf are gene models predicted by BRAKER. Those **DO NOT** represent the entire transcriptome. The difference between the files `combined_with_CDS_high_conf.gtf` and `combined_with_CDS_BRAKER_appended_high_conf.gtf` is that the former does not have any BRAKER gene predictions. So the file `combined_with_CDS_BRAKER_appended_high_conf.gtf` is a superset of `combined_with_CDS_high_conf.gtf` containing all the genes in `combined_with_CDS_high_conf.gtf` and only those BRAKER gene models that have protein level evidence. 

While it is a quick check to see the number of exons, you might be able to get a better picture if you extract the number of transcripts/gene models using the following commands.

Number of transcripts:
`cat <filename> |rev|cut -f1|rev|awk -F' ' '{print $2,$4}'|uniq|wc -l`

Number of genes:
`cat <filename> |rev|cut -f1|rev|awk -F' ' '{print $2}'|uniq|wc -l`

If you are looking for the absolutely final file then I recommend you take a look at `FINDER_BRAKER_PROT.gtf`. That file contains high confidence gene models, BRAKER predictions, and gene models constructed from protein sequences.

You could also review the output section https://github.com/sagnikbanerjee15/Finder#output-files in the README file.

Let me know if have any questions.

Thank you.

**Comment by josruirod** [comment]
Thanks, all looks clearer now. 
Best
